# Generated by Django 3.2 on 2021-04-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon_test_app', '0002_test_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
    ]
