# Generated by Django 3.2 on 2021-04-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon_test_app', '0003_humans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Humans',
            new_name='Human',
        ),
    ]
