# Generated by Django 3.2 on 2021-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon_test_app', '0004_rename_humans_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('result', models.FloatField()),
            ],
        ),
    ]
